POST http://localhost:4000/sineql HTTP/1.1
Content-Type: text/plain

Book {
	title
	published
}

###

POST http://localhost:4000/sineql HTTP/1.1
Content-Type: text/plain

create Book [
	{
		create title "The Philosopher's Kidney Stone"
	}
	{
		create title "The Chamber Pot of Secrets"
	}
	{
		create title "The Prisoner of Aunt Kazban"
	}
	{
		create title "The Goblet of the Fire Cocktail"
	}
	{
		create title "The Order for Kleenex"
	}
	{
		create title "The Half-Priced Pharmacy"
	}
	{
		create title "Yeah, I Got Nothing"
	}
]

###

POST http://localhost:4000/sineql HTTP/1.1
Content-Type: text/plain

update Book [
	{
		match title "The Philosopher's Kidney Stone"
		update published "1997-06-26"
	}
	{
		match title "The Chamber Pot of Secrets"
		update published "1998-07-02"
	}
	{
		match title "The Prisoner of Aunt Kazban"
		update published "1999-07-08"
	}
	{
		match title "The Goblet of the Fire Cocktail"
		update published "2000-07-08"
	}
	{
		match title "The Order for Kleenex"
		update published "2003-06-21"
	}
	{
		match title "The Half-Priced Pharmacy"
		update published "2005-07-16"
	}
	{
		match title "Yeah, I Got Nothing"
		update published "2007-07-21"
	}
]

###

POST http://localhost:4000/sineql HTTP/1.1
Content-Type: text/plain

create Author [
	{
		create name "Just Kidding"
		match books [
			{
				match title "Yeah, I Got Nothing"
			}
			{
				match title "The Half-Priced Pharmacy"
			}
		]
	}
	{
		create name "Mark Twain"
	}
]

###

